version: '3'

services:
  mq:
    image: hersonpc/rabbitmq
    hostname: mq
    ports:
      - "7000:15672"
      - "61613:61613"
    network_mode: "bridge"
    environment:
     - RABBITMQ_ERLANG_COOKIE=811bdf44dc6741a
     - RABBITMQ_DEFAULT_USER=mqadmin
     - RABBITMQ_DEFAULT_PASS=isgtecnologia_
     - RABBITMQ_USER=guest
     - RABBITMQ_PASSWORD=087we654zdf3218
     - CLUSTERED=true
