version: '3'

services:
  mq:
    image: hersonpc/rabbitmq
    hostname: mq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    network_mode: "bridge"
    environment:
     - RABBITMQ_ERLANG_COOKIE=811bdf44dc6741a
     - RABBITMQ_ADMIN_USER=mqadmin
     - RABBITMQ_ADMIN_PASS=isgtecnologia_
     - RABBITMQ_USER=guest
     - RABBITMQ_PASSWORD=guest
     - CLUSTERED=true
